
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from distutils.log import error
from pathlib import Path
import os

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

to_delete=['AnalysticsSettings.xml',
'frm.cfg',
'GlobalBasicSettings_13.xml']

def onclick():
    n = 0
    print("clicked")
    try:
        for i in Path(r"~\Appdata\Local\Roblox").expanduser().iterdir():
            if i.name in to_delete:
                print(f"{i.name} MATCH")
                os.remove(i)
                print(f"{i} deleted")
                n+=1
            else:
                pass
        messagebox.showinfo(f"Successful", f"We have deleted these file and you may now run roblox. ({n} files deleted)")
    except FileNotFoundError:
        print("You do not have roblox installed!")
        messagebox.showerror(f"File Not Found!", "You do not have roblox installed.")
        
window = Tk()
window.geometry("871x339")
window.configure(bg = "#3A7FF6")
from pathlib import Path
d = Path(__file__).parent
window.iconbitmap(d / "assets" / "lambda.ico")
window.title("Roblox    Kickfix")

canvas = Canvas(
    window,
    bg = "#3A7FF6",
    height = 339,
    width = 871,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    450.9999999999999,
    7.105427357601002e-15,
    870.9999999999999,
    339.0,
    fill="#FCFCFC",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=onclick,
    relief="flat"
)
button_1.place(
    x=570.9999999999999,
    y=138.0,
    width=180.0,
    height=55.0
)

canvas.create_text(
    45.999999999999886,
    63.00000000000001,
    anchor="nw",
    text="Welcome to Roblox Kick Fix (268)",
    fill="#FCFCFC",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_text(
    460.9999999999999,
    77.0,
    anchor="nw",
    text="This button will fix your 268 problem.",
    fill="#505485",
    font=("Roboto Bold", 24 * -1)
)

canvas.create_rectangle(
    45.999999999999886,
    99.0,
    408.9999999999999,
    104.0,
    fill="#FCFCFC",
    outline="")

canvas.create_rectangle(
    38.999999999999886,
    201.0,
    420.9999999999999,
    203.0,
    fill="#FCFCFC",
    outline="")

canvas.create_rectangle(
    39.999999999999886,
    285.0,
    420.9999999999999,
    287.0,
    fill="#FCFCFC",
    outline="")

canvas.create_rectangle(
    37.999999999999886,
    201.0,
    39.999999999999886,
    287.0,
    fill="#FCFCFC",
    outline="")

canvas.create_rectangle(
    418.9999999999999,
    201.0,
    420.9999999999999,
    287.0,
    fill="#FCFCFC",
    outline="")

canvas.create_text(
    45.999999999999886,
    127.0,
    anchor="nw",
    text="This program will fix your 268 problem by",
    fill="#FCFCFC",
    font=("Ubuntu Regular", 18 * -1)
)

canvas.create_text(
    45.999999999999886,
    151.0,
    anchor="nw",
    text="Deleting these file belows",
    fill="#FCFCFC",
    font=("Ubuntu Regular", 18 * -1)
)

canvas.create_text(
    8.999999999999886,
    317.0,
    anchor="nw",
    text="Made by Euphoria#2042",
    fill="#FCFCFC",
    font=("Ubuntu Regular", 13 * -1)
)

canvas.create_text(
    44.999999999999886,
    208.0,
    anchor="nw",
    text="AnalysticsSettings.xml",
    fill="#FCFCFC",
    font=("Ubuntu Regular", 18 * -1)
)

canvas.create_text(
    45.999999999999886,
    232.0,
    anchor="nw",
    text="frm.cfg",
    fill="#FCFCFC",
    font=("Ubuntu Regular", 18 * -1)
)

canvas.create_text(
    45.999999999999886,
    256.0,
    anchor="nw",
    text="GlobalBasicSettings_13.xml",
    fill="#FCFCFC",
    font=("Ubuntu Regular", 18 * -1)
)
window.resizable(False, False)
window.mainloop()
